version: '3.1'
services:
  user_api_postgresql:
    build:
      context: docker/databases/UserApiPostgreSQL
      dockerfile: Dockerfile.UserApiPostgreSQL
    container_name: user_api_postgresql_container
    ports:
      - "5433:5432"
    networks:
      - my_network

  user_api:
    build:
      context: .
      dockerfile: docker/services/Dockerfile.UserApi
    container_name: user_api_container
    ports:
      - "8090:8090"
    networks:
      - my_network

networks:
  my_network: